<?php
/**
 * TL_ROOT/system/modules/efg/languages/pl/tl_efg_modules.php 
 * 
 * TYPOlight extension: efg 1.10.4 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2008 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['formdata'] = "Magazyn danych";
$GLOBALS['TL_LANG']['MOD']['efg'] = "Magazyn danych";
$GLOBALS['TL_LANG']['MOD']['feedback']['0'] = "Wszystko";
$GLOBALS['TL_LANG']['MOD']['feedback']['1'] = "Magazynowanie danych z formularzy.";
$GLOBALS['TL_LANG']['MOD']['formdata_from'] = "Magazynowanie danych z formularza";
$GLOBALS['TL_LANG']['MOD']['formdatalisting']['0'] = "Lista EFG";
$GLOBALS['TL_LANG']['MOD']['formdatalisting']['1'] = "Ten moduł pozwala na wyświetlenie listy rekordów z konkretnej tabeli bazy danych na stronach serwisu.";
$GLOBALS['TL_LANG']['FMD']['formdatalisting']['0'] = "Lista EFG";
$GLOBALS['TL_LANG']['FMD']['formdatalisting']['1'] = "Użyj tego modułu do wyświetlenia listy rekordów z konkretnej tabeli bazy danych na stronach serwisu.";
$GLOBALS['TL_LANG']['tl_module']['list_formdata']['0'] = "Tabela danych formularza";
$GLOBALS['TL_LANG']['tl_module']['list_formdata']['1'] = "Wybierz tabelę bazy danych, której rekordy chcesz wyświetlić.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_fields']['0'] = "Pola";
$GLOBALS['TL_LANG']['tl_module']['efg_list_fields']['1'] = "Wybierz pola, które chcesz wyświtlić.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_searchtype']['0'] = "Typ formularza wyszukiwnia";
$GLOBALS['TL_LANG']['tl_module']['efg_list_searchtype']['1'] = "Zaznacz";
$GLOBALS['TL_LANG']['tl_module']['efg_list_search']['0'] = "Wyszukiwane pola";
$GLOBALS['TL_LANG']['tl_module']['efg_list_search']['1'] = "Zaznacz pola, które mają być wyszukiwane na stronach serwisu.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_info']['0'] = "Pola strony szczegółów";
$GLOBALS['TL_LANG']['tl_module']['efg_list_info']['1'] = "Zaznacz pola, które mają się pokazać na stronie szczegółów. Brak zaznaczonych pól wyłącza stronę szczegółów.";
$GLOBALS['TL_LANG']['tl_module']['efg_iconfolder']['0'] = "Folder ikon";
$GLOBALS['TL_LANG']['tl_module']['efg_iconfolder']['1'] = "Podaj folder, w którym znajdują sie Twoje ikony. Jeśli zostawisz to pole puste, użyte zostaną ikony z folderu \"system/modules/efg/html/\".";
$GLOBALS['TL_LANG']['tl_module']['efg_list_access']['0'] = "Restrykcje wyświetlania";
$GLOBALS['TL_LANG']['tl_module']['efg_list_access']['1'] = "Wybierz, które rekordy powinny być widoczne.";
$GLOBALS['TL_LANG']['tl_module']['efg_DetailsKey']['0'] = "Fragment adresu URL dla strony szczegułów";
$GLOBALS['TL_LANG']['tl_module']['efg_DetailsKey']['1'] = "Zamiast domyślnego fragmentu - \"details\" - możesz zdefiniować własny fragment, który będzi użyty w URL do strony szczegółów. Zaleca się nie używać polskich znaków diakrytycznych.<br />This way an URL like www.domain.tld/page/<b>info</b>/alias.html can be generated, whereas standard URL would be www.domain.tld/page/<b>details</b>/alias.html";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_edit_access']['0'] = "Edycja na stronie serwisu";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_edit_access']['1'] = "Wybierz tę opcję aby włączyć edycję rekordów na stronach serwisu.";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_delete_access']['0'] = "Usuwanie na stronie serwisu";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_delete_access']['1'] = "Wybierz tę opcję aby włączyć usuwanie rekordów na stronach serwisu.";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_export_access']['0'] = "Export CSV na stronie serwisu";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_export_access']['1'] = "Wybierz te opcję aby włączyć export danych jako plik CSV na stronach serwisu.";
$GLOBALS['TL_LANG']['efg_list_searchtype']['none']['0'] = "None";
$GLOBALS['TL_LANG']['efg_list_searchtype']['none']['1'] = "Brak formularza wyszukiwania";
$GLOBALS['TL_LANG']['efg_list_searchtype']['dropdown']['0'] = "Rozwijana lista i pole tekstowe";
$GLOBALS['TL_LANG']['efg_list_searchtype']['dropdown']['1'] = "Formularz wyszukiwania będzie zawierał jedną rozwijaną listę i jedno pole tekstowe do wyszukiwania.";
$GLOBALS['TL_LANG']['efg_list_searchtype']['singlefield']['0'] = "Pojedyncze pole wyszukiwnia";
$GLOBALS['TL_LANG']['efg_list_searchtype']['singlefield']['1'] = "Formularz wyszukiwania będzie zawierać jedno pole tekstowe.";
$GLOBALS['TL_LANG']['efg_list_searchtype']['multiplefields']['0'] = "Wielokrotne pole wyszukiwnia";
$GLOBALS['TL_LANG']['efg_list_searchtype']['multiplefields']['1'] = "Formularz wyszukiwania będzie zawierał jedno pole tekstowe dla każdego zdefiniowanego pola do wyszukiwania.";
$GLOBALS['TL_LANG']['efg_list_access']['public']['0'] = "Każdy";
$GLOBALS['TL_LANG']['efg_list_access']['public']['1'] = "Każdy odwiedzający stronę zobaczy wszystkie rekordy.";
$GLOBALS['TL_LANG']['efg_list_access']['member']['0'] = "Właściciel";
$GLOBALS['TL_LANG']['efg_list_access']['member']['1'] = "Członkowie mogą widzieć tylko własne rekordy.";
$GLOBALS['TL_LANG']['efg_list_access']['groupmembers']['0'] = "Grupa członków";
$GLOBALS['TL_LANG']['efg_list_access']['groupmembers']['1'] = "Członkowie mogą widzieć tylko własne rekordy i rekordy członków swojej grupy.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['none']['0'] = "Bez edycji na stronie serwisu";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['none']['1'] = "Rekordy nie będą mogły być edytowane na stronie serwisu.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['public']['0'] = "Każdy";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['public']['1'] = "Każdy odwiedzający bedzie mógł edytować wszystkie rekordy.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['member']['0'] = "Właściciel";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['member']['1'] = "Członkowie mogą edytować tylko własne rekordy.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['groupmembers']['0'] = "Grupa członków";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['groupmembers']['1'] = "Członkowie mogą edytować tylko własne rekordy i rekordy członków swojej grupy.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['none']['0'] = "Bez usuwania na stronie serwisu";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['none']['1'] = "Rekordy nie będą mogły być usuwane na stronie serwisu.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['public']['0'] = "Każdy";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['public']['1'] = "Każdy odwiedzający bedzie mógł usuwać wszystkie rekordy.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['member']['0'] = "Właściciel";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['member']['1'] = "Czlonkowie będą mogli usuwać tylko własne rekordy.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['groupmembers']['0'] = "Grupa członków";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['groupmembers']['1'] = "Członkowie mogą usuwać tylko własne rekordy i rekordy członków swojej grupy.";
$GLOBALS['TL_LANG']['efg_fe_export_access']['none']['0'] = "Bez exportu na stronie serwisu";
$GLOBALS['TL_LANG']['efg_fe_export_access']['none']['1'] = "Rekordy nie będą mogły być exportowane na stronie serwisu.";
$GLOBALS['TL_LANG']['efg_fe_export_access']['public']['0'] = "Każdy";
$GLOBALS['TL_LANG']['efg_fe_export_access']['public']['1'] = "Każdy odwiedzający stronę może exportować wszystkie rekordy.";
$GLOBALS['TL_LANG']['efg_fe_export_access']['member']['0'] = "Właściciel";
$GLOBALS['TL_LANG']['efg_fe_export_access']['member']['1'] = "Członkowie mogą exportować tylko własne rekordy.";
$GLOBALS['TL_LANG']['efg_fe_export_access']['groupmembers']['0'] = "Grupa członków";
$GLOBALS['TL_LANG']['efg_fe_export_access']['groupmembers']['1'] = "Członkowie mogą exportować tylko własne rekordy i rekordy członków swojej grupy.";
 
?>
