<?php
/**
 * TL_ROOT/system/modules/efg/languages/pl/tl_form.php 
 * 
 * TYPOlight extension: efg 1.10.4 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2008 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_form']['storeFormdata']['0'] = "Magazynuj dane w module \"Magazyn danych\"";
$GLOBALS['TL_LANG']['tl_form']['storeFormdata']['1'] = "Jeśli zaznaczysz tę opcję, dane będą magazynowane w bazie danych.<br>Pamiętaj: Zapisz formularz po każdej jego modyfikacji.";
$GLOBALS['TL_LANG']['tl_form']['efgAliasField']['0'] = "Pole formularza jako alias";
$GLOBALS['TL_LANG']['tl_form']['efgAliasField']['1'] = "Wybrane pole formularza będzie użyte do wygenerowania aliasu dla danych z formularza.";
$GLOBALS['TL_LANG']['tl_form']['efgStoreValues']['0'] = "Zapisz wartości";
$GLOBALS['TL_LANG']['tl_form']['efgStoreValues']['1'] = "Wybierz tę opcję jeśli chcesz zachować wartości zamiast etykietek pól formularza typu pola jedno lub wielokrotnego wyboru oraz listę rozwijaną";
$GLOBALS['TL_LANG']['tl_form']['useFormValues']['0'] = "Exportuj wartości pól";
$GLOBALS['TL_LANG']['tl_form']['useFormValues']['1'] = "Jeśli wybierzesz tę opcję, podczas exportu będą exportowane nazwy pól zamiast etykietek pól. Dotyczy to pól typu  jedno lub wielokrotnego wyboru oraz listy rozwijanej";
$GLOBALS['TL_LANG']['tl_form']['useFieldNames']['0'] = "Exportuj nazwy pól";
$GLOBALS['TL_LANG']['tl_form']['useFieldNames']['1'] = "Jeśli wybierzesz tę opcję, podczas exportu będą exportowane nazwy pól zamiast etykietek pól.";
$GLOBALS['TL_LANG']['tl_form']['sendConfirmationMail']['0'] = "Wyślij potwierdzenie poprzez email";
$GLOBALS['TL_LANG']['tl_form']['sendConfirmationMail']['1'] = "Jeśli wybierzesz tę opcję, potwierdzenie będzie wysłane poprzez email do autora wpisu.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailRecipientField']['0'] = "Pole formularza zawierające e-mail odbiorcy";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailRecipientField']['1'] = "Wybierz pole formularza, w które użytkownik wprowadza swój adres email lub ople zawierające adres email jako wartość.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailRecipient']['0'] = "Odbiorca";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailRecipient']['1'] = "Wprowadź jeden lub wiele adresów email odbiorców jeśli adres email nie jest zdefiniowany w polu formularza lub jeśli chcesz emaila do dodatkowych odbiorców. Oddziel każdy adres przecinkiem.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailSender']['0'] = "Nadawca";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailSender']['1'] = "Wprowadź adres email, który będzie użyty jako nadawca.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailSubject']['0'] = "Temat";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailSubject']['1'] = "Wpisz temat maila potwierdzającego. Jeśli nie wpiszesz tematu, wzrośnie prawdopodobieństwo zakwalifikowania Twojego emaila jako SPAM.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailText']['0'] = "Tekst maila potwierdzającego.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailText']['1'] = "Wprowadź tekst maila potwierdzającego. Możesz używać standardowych tagów oraz tagów takich jak: form::NAZWA_POLA .";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailTemplate']['0'] = "Szablon HTML dla maila potwierdzającego";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailTemplate']['1'] = "Jeśli mail potwierdzający powinien być wysłany jako mail HTML, wybierz swój szablon HTML.";
$GLOBALS['TL_LANG']['tl_form']['sendFormattedMail']['0'] = "Wyślij dane z formularza w mailu (tekst formatowany lub HTML)";
$GLOBALS['TL_LANG']['tl_form']['sendFormattedMail']['1'] = "Tekst maila może być zdefiniowany z użyciem tagów. Mail może być wysłany jako mail HTML.";
$GLOBALS['TL_LANG']['tl_form']['formattedMailText']['0'] = "Tekst maila";
$GLOBALS['TL_LANG']['tl_form']['formattedMailText']['1'] = "Wprowadź tekst maila. Możesz używać standardowych tagów oraz tagów takich jak: form::NAZWA_POLA .";
$GLOBALS['TL_LANG']['tl_form']['formattedMailTemplate']['0'] = "Szablon HTML dla maila";
$GLOBALS['TL_LANG']['tl_form']['formattedMailTemplate']['1'] = "Jeśli mail potwierdzający powinien być wysłany jako mail HTML, wybierz swój szablon HTML.";
 
?>
