<?php
/**
 * TL_ROOT/system/modules/efg/languages/nl/tl_efg_modules.php 
 * 
 * TYPOlight extension: efg 1.10.4 stable 
 * Dutch translation file 
 * 
 * Copyright : (c) 2008 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['formdata'] = "Formuliergegevens";
$GLOBALS['TL_LANG']['MOD']['efg'] = "Formuliergegevens";
$GLOBALS['TL_LANG']['MOD']['feedback']['0'] = "Alle resultaten";
$GLOBALS['TL_LANG']['MOD']['feedback']['1'] = "Opgeslagen gegevens uit formulieren.";
$GLOBALS['TL_LANG']['MOD']['formdata_from'] = "Opgeslagen gegevens uit een formulier";
$GLOBALS['TL_LANG']['MOD']['formdatalisting']['0'] = "Toon formuliergegevens";
$GLOBALS['TL_LANG']['MOD']['formdatalisting']['1'] = "Deze module toont de records van een bepaalde formuliergegevens-tabel in het frontend.";
$GLOBALS['TL_LANG']['FMD']['formdatalisting']['0'] = "Toon formuliergegevens";
$GLOBALS['TL_LANG']['FMD']['formdatalisting']['1'] = "Deze module toont de records van een bepaalde formuliergegevens-tabel in het frontend.";
$GLOBALS['TL_LANG']['tl_module']['list_formdata']['0'] = "Formuliergegevens-tabel";
$GLOBALS['TL_LANG']['tl_module']['list_formdata']['1'] = "Kies de formuliergegevens-tabel die u wilt tonen.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_fields']['0'] = "Velden";
$GLOBALS['TL_LANG']['tl_module']['efg_list_fields']['1'] = "Kies de velden die u wilt tonen.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_searchtype']['0'] = "Soort zoekformulier";
$GLOBALS['TL_LANG']['tl_module']['efg_list_searchtype']['1'] = "Kies het soort zoekformulier dat u wilt gebruiken.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_search']['0'] = "Te doorzoeken velden";
$GLOBALS['TL_LANG']['tl_module']['efg_list_search']['1'] = "Kies de velden die te doorzoeken moeten zijn in het frontend.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_info']['0'] = "Detailpagina velden";
$GLOBALS['TL_LANG']['tl_module']['efg_list_info']['1'] = "Kies de velden die op de detailpagina moeten verschijnen. Kies niets om de detailpagina-mogelijkheid niet te gebruiken.";
$GLOBALS['TL_LANG']['tl_module']['efg_iconfolder']['0'] = "Icoonmap";
$GLOBALS['TL_LANG']['tl_module']['efg_iconfolder']['1'] = "Geef de map waarin uw iconen staan. Als u niets invult worden de iconen in \"system/modules/efg/html/\" gebruikt.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_access']['0'] = "Weergave restrictie";
$GLOBALS['TL_LANG']['tl_module']['efg_list_access']['1'] = "Kies welke records zichtbaar moeten zijn.";
$GLOBALS['TL_LANG']['tl_module']['efg_DetailsKey']['0'] = "URL fragment voor detailpagina";
$GLOBALS['TL_LANG']['tl_module']['efg_DetailsKey']['1'] = "Hier kunt u een ander begrip opgeven in plaats van de default waarde \"details\" die gebruikt wordt in de URL voor een detailpagina.<br />Op deze wijze wordt een URL als www.domain.tld/page/<b>info</b>/alias.html gegenereerd, in plaats van de standaard URL www.domain.tld/page/<b>details</b>/alias.html";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_edit_access']['0'] = "Frontend bewerking";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_edit_access']['1'] = "Kies als records via het frontend bewerkt moeten kunnen worden.";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_delete_access']['0'] = "Frontend wissen";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_delete_access']['1'] = "Kies als records via het frontend gewist moeten kunnen worden.";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_export_access']['0'] = "Frontend CSV export";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_export_access']['1'] = "Kies als records via het frontend geëxporteerd moeten kunnen worden als CSV-bestand.";
$GLOBALS['TL_LANG']['efg_list_searchtype']['none']['0'] = "Geen";
$GLOBALS['TL_LANG']['efg_list_searchtype']['none']['1'] = "Geen zoekformulier";
$GLOBALS['TL_LANG']['efg_list_searchtype']['dropdown']['0'] = "Dropdown en tekstveld";
$GLOBALS['TL_LANG']['efg_list_searchtype']['dropdown']['1'] = "Het zoekformulier bevat één dropdown-menu (om het veld te kiezen waarin gezocht moet worden) en een tekstveld om het zoekbegrip in te vullen.";
$GLOBALS['TL_LANG']['efg_list_searchtype']['singlefield']['0'] = "Enkel zoekveld";
$GLOBALS['TL_LANG']['efg_list_searchtype']['singlefield']['1'] = "Het zoekformulier bevat slechts één tekstveld. De zoekactie wordt uitgevoerd op alle opgegeven zoekvelden.";
$GLOBALS['TL_LANG']['efg_list_searchtype']['multiplefields']['0'] = "Meerdere zoekvelden";
$GLOBALS['TL_LANG']['efg_list_searchtype']['multiplefields']['1'] = "Het zoekformulier bevat één tekstveld voor elk opgegeven zoekveld.";
$GLOBALS['TL_LANG']['efg_list_access']['public']['0'] = "Openbaar";
$GLOBALS['TL_LANG']['efg_list_access']['public']['1'] = "Elke bezoeker mag alle records zien.";
$GLOBALS['TL_LANG']['efg_list_access']['member']['0'] = "Eigenaar";
$GLOBALS['TL_LANG']['efg_list_access']['member']['1'] = "Leden mogen alleen hun eigen records zien.";
$GLOBALS['TL_LANG']['efg_list_access']['groupmembers']['0'] = "Groepsleden";
$GLOBALS['TL_LANG']['efg_list_access']['groupmembers']['1'] = "Leden mogen alleen hun eigen records en die van hun groepsleden zien.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['none']['0'] = "Geen frontend wijzigingen";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['none']['1'] = "Records kunnen niet gewijzigd worden via het frontend.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['public']['0'] = "Openbaar";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['public']['1'] = "Elke bezoeker mag alle records wijzigen.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['member']['0'] = "Eigenaar";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['member']['1'] = "Leden mogen alleen hun eigen records wijzigen.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['groupmembers']['0'] = "Groepsleden";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['groupmembers']['1'] = "Leden mogen alleen hun eigen records en die van hun groepsleden wijzigen.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['none']['0'] = "Geen frontend wissen";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['none']['1'] = "Records kunnen niet gewist worden via het frontend.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['public']['0'] = "Openbaar";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['public']['1'] = "Elke bezoeker mag alle records wissen.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['member']['0'] = "Eigenaar";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['member']['1'] = "Leden mogen alleen hun eigen records wissen.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['groupmembers']['0'] = "Groepsleden";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['groupmembers']['1'] = "Leden mogen alleen hun eigen records en die van hun groepsleden wissen.";
$GLOBALS['TL_LANG']['efg_fe_export_access']['none']['0'] = "Geen frontend export";
$GLOBALS['TL_LANG']['efg_fe_export_access']['none']['1'] = "Records kunnen niet geëxporteerd worden via het frontend.";
$GLOBALS['TL_LANG']['efg_fe_export_access']['public']['0'] = "Openbaar";
$GLOBALS['TL_LANG']['efg_fe_export_access']['public']['1'] = "Elke bezoeker mag alle records exporteren.";
$GLOBALS['TL_LANG']['efg_fe_export_access']['member']['0'] = "Eigenaar";
$GLOBALS['TL_LANG']['efg_fe_export_access']['member']['1'] = "Leden mogen alleen hun eigen records exporteren.";
$GLOBALS['TL_LANG']['efg_fe_export_access']['groupmembers']['0'] = "Groepsleden";
$GLOBALS['TL_LANG']['efg_fe_export_access']['groupmembers']['1'] = "Leden mogen alleen hun eigen records en die van hun groepsleden exporteren.";
 
?>
