<?php
/**
 * TL_ROOT/system/modules/efg/languages/nl/tl_form_field.php 
 * 
 * TYPOlight extension: efg 1.10.4 stable 
 * Dutch translation file 
 * 
 * Copyright : (c) 2008 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FFL']['efgLookupSelect']['0'] = "Selecteer menu (DB)";
$GLOBALS['TL_LANG']['FFL']['efgLookupSelect']['1'] = "Selecteer menu (DB) is een drop down menu van één regel dat verschillende opties bevat waaruit één kan geselecteerd worden. De opties komen in dit geval uit een opgegeven database tabel.";
$GLOBALS['TL_LANG']['FFL']['efgLookupCheckbox']['0'] = "Checkbox menu (DB)";
$GLOBALS['TL_LANG']['FFL']['efgLookupCheckbox']['1'] = "Checkbox menu (DB) bestaat uit meerdere regels en bevat verschillende opties waaruit meerdere geselecteerd kunnen worden. De opties komen in dit geval uit een opgegeven database tabel.";
$GLOBALS['TL_LANG']['FFL']['efgLookupRadio']['0'] = "Radio button menu (DB)";
$GLOBALS['TL_LANG']['FFL']['efgLookupRadio']['1'] = "Radio button menu (DB) bestaat uit meerdere regels en bevat verschillende opties waaruit één kan worden geselecteerd. De opties komen in dit geval uit een opgegeven database tabel.";
$GLOBALS['TL_LANG']['FFL']['efgImageSelect']['0'] = "Afbeelding selectiemenu";
$GLOBALS['TL_LANG']['FFL']['efgImageSelect']['1'] = "Dit menu geeft in het formulier een afbeeldingsgalerij met radiobuttons.";
$GLOBALS['TL_LANG']['tl_form_field']['efgLookupOptions']['0'] = "Opties uit database";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_field']['0'] = "Databaseveld (label)";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_field']['1'] = "Kies het databaseveld waaruit de mogelijke opties (labels) gehaald moeten worden.";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_val_field']['0'] = "Databaseveld (waarde)";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_val_field']['1'] = "Kies het databaseveld waaruit de mogelijke opties (waarden) gehaald moeten worden.";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_where']['0'] = "Voorwaarde";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_where']['1'] = "Als u bepaalde records wilt uitsluiten, dan kunt u hier de voorwaarde opgeven (bv. <em>published='1'</em> of <em>type!='admin'</em>).";
$GLOBALS['TL_LANG']['tl_form_field']['efgMultiSRC']['0'] = "Bronbestanden";
$GLOBALS['TL_LANG']['tl_form_field']['efgMultiSRC']['1'] = "Kies één of meer bestanden of mappen (bestanden in een gekozen map worden automatisch allemaal meegenomen).";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSortBy']['0'] = "Sorteer op";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSortBy']['1'] = "Selecteer de sorteervolgorde.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSize']['0'] = "Afbeeldingsbreedte en -hoogte";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSize']['1'] = "Geef ofwel de afbeeldingsbreedte, de afbeeldingshoogte of beide op om de grootte van afbeelding aan te passen. Als u beide velden leeg laat zal de originele afbeeldingsgrootte worden weergegeven.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImagePerRow']['0'] = "Thumbnails per regel";
$GLOBALS['TL_LANG']['tl_form_field']['efgImagePerRow']['1'] = "Geef het aantal thumbnails per regel op.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageMargin']['0'] = "Afbeeldingsmarge";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageMargin']['1'] = "Geef de top, right, bottom and left margin en de eenheid op. Afbeeldingsmarge is de afstand tussen een afbeelding en de naastliggende elementen.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageFullsize']['0'] = "Ware grootte";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageFullsize']['1'] = "Als u deze optie kiest kan de volledige afbeelding bekeken worden door er op te klikken.";
$GLOBALS['TL_LANG']['tl_form_field']['name_asc'] = "Bestandsnaam (oplopend)";
$GLOBALS['TL_LANG']['tl_form_field']['name_desc'] = "Bestandsnaam (aflopend)";
$GLOBALS['TL_LANG']['tl_form_field']['date_asc'] = "Datum (oplopend)";
$GLOBALS['TL_LANG']['tl_form_field']['date_desc'] = "Datum (aflopend)";
$GLOBALS['TL_LANG']['tl_form_field']['meta'] = "Metafile (meta.txt)";
 
?>
