<?php
/**
 * TL_ROOT/system/modules/efg/languages/nl/tl_form.php 
 * 
 * TYPOlight extension: efg 1.12.0 stable 
 * Dutch translation file 
 * 
 * Copyright : (c) 2009 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_form']['storeFormdata']['0'] = "Sla gegevens op in de module \"Form data\"";
$GLOBALS['TL_LANG']['tl_form']['storeFormdata']['1'] = "Formuliergegevens zullen opgeslagen worden in de database \"Form data\".<br>NB. Bewaar dit formulier steeds nadat velden zijn toegevoegd of gewijzigd.";
$GLOBALS['TL_LANG']['tl_form']['efgAliasField']['0'] = "Formulierveld voor Alias";
$GLOBALS['TL_LANG']['tl_form']['efgAliasField']['1'] = "Kies het veld dat gebruikt wordt om het alias van de formuliergegevens te genereren.";
$GLOBALS['TL_LANG']['tl_form']['efgStoreValues']['0'] = "Bewaar waarden van opties";
$GLOBALS['TL_LANG']['tl_form']['efgStoreValues']['1'] = "Kies dit als u de waarde (value) wil bewaren in plaats van het label van radiobuttons, checkboxes en selects.";
$GLOBALS['TL_LANG']['tl_form']['useFormValues']['0'] = "Exporteer veldwaarden";
$GLOBALS['TL_LANG']['tl_form']['useFormValues']['1'] = "Als u dit kiest worden voor de geselecteerde velden veldwaarden geëxporteerd in plaats van veldkenmerken. Dit geldt alleen voor radiobuttons, checkboxes en selects.";
$GLOBALS['TL_LANG']['tl_form']['useFieldNames']['0'] = "Exporteer veldnamen";
$GLOBALS['TL_LANG']['tl_form']['useFieldNames']['1'] = "Als u dit kiest worden veldnamen geëxporteerd in plaats van veldlabels.";
$GLOBALS['TL_LANG']['tl_form']['sendConfirmationMail']['0'] = "Stuur bevestiging via e-mail";
$GLOBALS['TL_LANG']['tl_form']['sendConfirmationMail']['1'] = "Stuur degene die het formulier ingevuld en verzonden heeft een bevestiging via e-mail.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailRecipientField']['0'] = "Veld waarin het e-mailadres van de ontvanger staat";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailRecipientField']['1'] = "Kies het veld waarin de gebruiker zijn e-mailadres heeft ingevuld of het veld waarin het e-mailadres als waarde staat.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailRecipient']['0'] = "Ontvanger(s)";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailRecipient']['1'] = "Geef één of meerdere e-mailadressen als het e-mailadres niet in het formulier staat of als de e-mail ook naar andere adressen gestuurd moet worden. Meerdere adressen scheiden met komma's.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailSender']['0'] = "Afzender";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailSender']['1'] = "Het e-mailadres dat als afzender gebruikt wordt.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailSubject']['0'] = "Onderwerp";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailSubject']['1'] = "Het onderwerp van de bevestigingsmail. Niet verplicht om in te vullen maar wel zeer aan te raden, om te voorkomen dat de mail als spam wordt aangemerkt.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailText']['0'] = "Tekst van bevestigingsmail";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailText']['1'] = "De tekst van de bevestigingsmail. U kan gebruik maken van standaard insert tags en tags zoals form::NAME_OF_FORMFIELD .";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailTemplate']['0'] = "HTML-sjabloon voor bevestigingsmail";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailTemplate']['1'] = "Als de bevestigingsmail verstuurd moet worden als HTML-mail, kies dan een HTML-sjabloon uit het bestandssysteem.";
$GLOBALS['TL_LANG']['tl_form']['sendFormattedMail']['0'] = "Verstuur formuliergegevens via e-mail";
$GLOBALS['TL_LANG']['tl_form']['sendFormattedMail']['1'] = "De tekst van de mail kan gedefinieerd worden m.b.v. insert tags. HTML-mail is ook mogelijk.";
$GLOBALS['TL_LANG']['tl_form']['formattedMailText']['0'] = "Mailtekst";
$GLOBALS['TL_LANG']['tl_form']['formattedMailText']['1'] = "Tekst van de mail. U kan gebruik maken van standaard insert tags en tags zoals form::NAME_OF_FORMFIELD .";
$GLOBALS['TL_LANG']['tl_form']['formattedMailTemplate']['0'] = "HTML-sjabloon voor e-mail";
$GLOBALS['TL_LANG']['tl_form']['formattedMailTemplate']['1'] = "Als de e-mail verstuurd moet worden als HTML-mail, kies dan een HTML-sjabloon uit het bestandssysteem.";
$GLOBALS['TL_LANG']['tl_form']['efgStoreFormdata_legend'] = "(EFG) Bewaar formuliergegevens";
$GLOBALS['TL_LANG']['tl_form']['efgSendFormattedMail_legend'] = "(EFG) Verstuur via e-mail";
$GLOBALS['TL_LANG']['tl_form']['efgSendConfirmationMail_legend'] = "(EFG) Verstuur bevestiging via e-mail";
 
?>
