<?php
/**
 * TL_ROOT/system/modules/efg/languages/nl/tl_formdata.php 
 * 
 * TYPOlight extension: efg 1.12.0 stable 
 * Dutch translation file 
 * 
 * Copyright : (c) 2009 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_formdata']['form']['0'] = "Formulier";
$GLOBALS['TL_LANG']['tl_formdata']['form']['1'] = "Gegevens uit formulier";
$GLOBALS['TL_LANG']['tl_formdata']['date']['0'] = "Datum";
$GLOBALS['TL_LANG']['tl_formdata']['date']['1'] = "Inschrijvingsdatum";
$GLOBALS['TL_LANG']['tl_formdata']['ip']['0'] = "IP adres";
$GLOBALS['TL_LANG']['tl_formdata']['ip']['1'] = "IP adres van afzender";
$GLOBALS['TL_LANG']['tl_formdata']['be_notes']['0'] = "Aantekeningen";
$GLOBALS['TL_LANG']['tl_formdata']['be_notes']['1'] = "Aantekeningen, todolijsten etc.";
$GLOBALS['TL_LANG']['tl_formdata']['published']['0'] = "Gepubliceerd";
$GLOBALS['TL_LANG']['tl_formdata']['published']['1'] = "Gebruik deze optie als weergave-conditie als u een list module gebruikt.";
$GLOBALS['TL_LANG']['tl_formdata']['fd_member']['0'] = "Lid";
$GLOBALS['TL_LANG']['tl_formdata']['fd_member']['1'] = "Lid als eigenaar van dit record";
$GLOBALS['TL_LANG']['tl_formdata']['fd_user']['0'] = "Gebruiker";
$GLOBALS['TL_LANG']['tl_formdata']['fd_user']['1'] = "Gebruiker als eigenaar van dit record";
$GLOBALS['TL_LANG']['tl_formdata']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_formdata']['alias']['1'] = "Een unieke verwijzing naar het record dat gebruikt kan worden in plaats van het record ID.";
$GLOBALS['TL_LANG']['tl_formdata']['new']['0'] = "Nieuw record";
$GLOBALS['TL_LANG']['tl_formdata']['new']['1'] = "Maak een nieuw record";
$GLOBALS['TL_LANG']['tl_formdata']['edit']['0'] = "Wijzig record";
$GLOBALS['TL_LANG']['tl_formdata']['edit']['1'] = "Wijzig record ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['copy']['0'] = "Dupliceer record";
$GLOBALS['TL_LANG']['tl_formdata']['copy']['1'] = "Dupliceer record ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['delete']['0'] = "Wis record";
$GLOBALS['TL_LANG']['tl_formdata']['delete']['1'] = "Wis record ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['show']['0'] = "Record details";
$GLOBALS['TL_LANG']['tl_formdata']['show']['1'] = "Toon de details van record ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['mail']['0'] = "Stuur een bevestigingsmail";
$GLOBALS['TL_LANG']['tl_formdata']['mail']['1'] = "Stuur een bevestigingsmail voor record ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['mail_sent'] = "Mail is gestuurd naar %s";
$GLOBALS['TL_LANG']['tl_formdata']['export']['0'] = "CSV export";
$GLOBALS['TL_LANG']['tl_formdata']['export']['1'] = "Exporteer records naar een CSV bestand";
$GLOBALS['TL_LANG']['tl_formdata']['exportxls']['0'] = "Excel export";
$GLOBALS['TL_LANG']['tl_formdata']['exportxls']['1'] = "Exporteer records naar een MS Excel bestand";
$GLOBALS['TL_LANG']['tl_formdata']['mail_sender']['0'] = "Afzender";
$GLOBALS['TL_LANG']['tl_formdata']['mail_sender']['1'] = "E-mailadres van de afzender";
$GLOBALS['TL_LANG']['tl_formdata']['mail_recipient']['0'] = "Ontvanger";
$GLOBALS['TL_LANG']['tl_formdata']['mail_recipient']['1'] = "E-mailadres van de ontvanger";
$GLOBALS['TL_LANG']['tl_formdata']['mail_subject']['0'] = "Onderwerp";
$GLOBALS['TL_LANG']['tl_formdata']['mail_subject']['1'] = "Onderwerp van de bevestigingsmail";
$GLOBALS['TL_LANG']['tl_formdata']['mail_body_plaintext']['0'] = "Boodschap (platte tekst)";
$GLOBALS['TL_LANG']['tl_formdata']['mail_body_plaintext']['1'] = "Tekst van de mail als platte tekst";
$GLOBALS['TL_LANG']['tl_formdata']['mail_body_html']['0'] = "Boodschap (HTML)";
$GLOBALS['TL_LANG']['tl_formdata']['mail_body_html']['1'] = "Tekst van de mail als HTML";
$GLOBALS['TL_LANG']['tl_formdata']['attachments'] = "Bijlagen";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_details']['0'] = "Details";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_details']['1'] = "Toon details";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_edit']['0'] = "Bewerk";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_edit']['1'] = "Bewerk record";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_delete']['0'] = "Wis";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_delete']['1'] = "Wis record";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_export']['0'] = "CSV Export";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_export']['1'] = "Exporteer record als een CSV bestand";
$GLOBALS['TL_LANG']['tl_formdata']['fe_deleteConfirm'] = "Wilt u de invoer werkelijk wissen?";
$GLOBALS['TL_LANG']['tl_formdata']['fdNotes_legend'] = "Aantekeningen";
$GLOBALS['TL_LANG']['tl_formdata']['fdOwner_legend'] = "Eigenaar";
$GLOBALS['TL_LANG']['tl_formdata']['fdDetails_legend'] = "Details";
 
?>
