<?php
/**
 * TL_ROOT/system/modules/efg/languages/it/tl_form_field.php 
 * 
 * TYPOlight extension: efg 1.10.1 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2008 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Cristiano Gazzi (kroom), www.roomk.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FFL']['efgLookupSelect']['0'] = "Menu selezione (DB)";
$GLOBALS['TL_LANG']['FFL']['efgLookupSelect']['1'] = "Il menu a selezione (DB) è un menu a discesa che contiene varie opzioni delle quali solo una può essere selezionata (select menu). Le opzioni sono estratte da una tavola definibile del database.";
$GLOBALS['TL_LANG']['FFL']['efgLookupCheckbox']['0'] = "Menu checkbox (DB)";
$GLOBALS['TL_LANG']['FFL']['efgLookupCheckbox']['1'] = "Il menu checkbox (DB) è un menu multi-linea che contiene una o più opzioni che possono essere selezionate anche simultaneamente. Le opzioni sono estratte da una tavola definibile del database.";
$GLOBALS['TL_LANG']['FFL']['efgLookupRadio']['0'] = "Menu opzioni (DB)";
$GLOBALS['TL_LANG']['FFL']['efgLookupRadio']['1'] = "Il menu a opzioni (DB) è un menu multi-linea che contiene  più opzioni delle quali solo una può essere selezionata (radio button menu). Le opzioni sono estratte da una tavola definibile del database.";
$GLOBALS['TL_LANG']['FFL']['efgImageSelect']['0'] = "Menu selezione immagini";
$GLOBALS['TL_LANG']['FFL']['efgImageSelect']['1'] = "Il menu selezione immagini produce una galleria fotografica con pulsanti radio nel modulo.";
$GLOBALS['TL_LANG']['tl_form_field']['efgLookupOptions']['0'] = "Opzioni dal database";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_field']['0'] = "Campo del database (etichetta)";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_field']['1'] = "Scegliere il campo del database dal quale estrarre le opzioni disponibili (etichetta).";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_val_field']['0'] = "Campo del database (valore)";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_val_field']['1'] = "Scegliere il campo del database dal quale estrarre le opzioni disponibili (valore).";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_where']['0'] = "Condizione";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_where']['1'] = "Se vuoi escludere certi record, puoi inserire una condizione di visualizzazione qui (es. <em>published=1</em> oppure <em>type!='admin'</em>";
$GLOBALS['TL_LANG']['tl_form_field']['efgMultiSRC']['0'] = "File origine";
$GLOBALS['TL_LANG']['tl_form_field']['efgMultiSRC']['1'] = "Seleziona uno o più file o cartelle (i file dentro le cartelle selezionate sarano inclusi automaticamente)";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSortBy']['0'] = "Ordina per";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSortBy']['1'] = "Seleziona un tipo di ordinamento.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSize']['0'] = "Larghezza e altezza dell'immagine";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSize']['1'] = "Inserisci una larghezza, un'altezza o entrambe i parametri per il ridimensionamento dell'immagine. Se lasci entrambe i campi vuoti, l'immagine sarà visualizzata con la dimensione originale.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImagePerRow']['0'] = "Miniature per riga";
$GLOBALS['TL_LANG']['tl_form_field']['efgImagePerRow']['1'] = "Inserisci il numero di miniature per riga.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageMargin']['0'] = "Margine dell'immagine";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageMargin']['1'] = "Inserisci il margine in alto, a destra, in basso, a sinistra e l'unità di misura. il margine dell'immagine è lo spazio tra l'immagine e gli elementi vicini.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageFullsize']['0'] = "Vista a dimensione piena";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageFullsize']['1'] = "Se scegli questa opzione, l'immagine può essere vista a dimensione piena cliccandoci sopra.";
$GLOBALS['TL_LANG']['tl_form_field']['name_asc'] = "Nome file (ascendente)";
$GLOBALS['TL_LANG']['tl_form_field']['name_desc'] = "Nome file (discendente)";
$GLOBALS['TL_LANG']['tl_form_field']['date_asc'] = "Data (ascendente)";
$GLOBALS['TL_LANG']['tl_form_field']['date_desc'] = "Data (discendente)";
$GLOBALS['TL_LANG']['tl_form_field']['meta'] = "Meta file (meta.txt)";
 
?>
