<?php
/**
 * TL_ROOT/system/modules/efg/languages/pl/tl_formdata.php 
 * 
 * TYPOlight extension: efg 1.10.4 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2008 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_formdata']['form']['0'] = "Formularz";
$GLOBALS['TL_LANG']['tl_formdata']['form']['1'] = "Dane z formularza";
$GLOBALS['TL_LANG']['tl_formdata']['date']['0'] = "Data";
$GLOBALS['TL_LANG']['tl_formdata']['date']['1'] = "Data wpisu";
$GLOBALS['TL_LANG']['tl_formdata']['ip']['0'] = "Adres IP";
$GLOBALS['TL_LANG']['tl_formdata']['ip']['1'] = "Adres IP nadawcy";
$GLOBALS['TL_LANG']['tl_formdata']['be_notes']['0'] = "Notatki";
$GLOBALS['TL_LANG']['tl_formdata']['be_notes']['1'] = "Notatki itp.";
$GLOBALS['TL_LANG']['tl_formdata']['published']['0'] = "Opublikowany";
$GLOBALS['TL_LANG']['tl_formdata']['published']['1'] = "Możesz użyć tej opcji jako warunku wyświetlania w module \"Lista EFG\".";
$GLOBALS['TL_LANG']['tl_formdata']['fd_member']['0'] = "Członek";
$GLOBALS['TL_LANG']['tl_formdata']['fd_member']['1'] = "Członek jako właściciel tego rekordu";
$GLOBALS['TL_LANG']['tl_formdata']['fd_user']['0'] = "Użytkownik";
$GLOBALS['TL_LANG']['tl_formdata']['fd_user']['1'] = "Użytkownik jako właściciel tego rekordu";
$GLOBALS['TL_LANG']['tl_formdata']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_formdata']['alias']['1'] = "Alias jest unikalnym odwołaniem do rekordu, które może być używane zamiast ID rekordu.";
$GLOBALS['TL_LANG']['tl_formdata']['new']['0'] = "Nowy rekord";
$GLOBALS['TL_LANG']['tl_formdata']['new']['1'] = "Utwórz nowy rekord";
$GLOBALS['TL_LANG']['tl_formdata']['edit']['0'] = "Edytuj rekord";
$GLOBALS['TL_LANG']['tl_formdata']['edit']['1'] = "Edytuj rekord ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['copy']['0'] = "Duplikuj rekord";
$GLOBALS['TL_LANG']['tl_formdata']['copy']['1'] = "Duplikuj rekord ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['delete']['0'] = "Usuń rekord";
$GLOBALS['TL_LANG']['tl_formdata']['delete']['1'] = "Usuń rekord ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['show']['0'] = "Szczegóły rekordu";
$GLOBALS['TL_LANG']['tl_formdata']['show']['1'] = "Pokaż szczegóły rekordu ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['mail']['0'] = "Wyślij maila potwierdzającego";
$GLOBALS['TL_LANG']['tl_formdata']['mail']['1'] = "Wyślij maila potwierdzającego dla rekordu ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['mail_sent'] = "Mail został wysłany do %s";
$GLOBALS['TL_LANG']['tl_formdata']['export']['0'] = "Export CSV";
$GLOBALS['TL_LANG']['tl_formdata']['export']['1'] = "Export rekordów do pliku CSV";
$GLOBALS['TL_LANG']['tl_formdata']['exportxls']['0'] = "Expot Excel";
$GLOBALS['TL_LANG']['tl_formdata']['exportxls']['1'] = "Export rekordów do pliku MS Excel";
$GLOBALS['TL_LANG']['tl_formdata']['mail_sender']['0'] = "Nadawca";
$GLOBALS['TL_LANG']['tl_formdata']['mail_sender']['1'] = "Adres email nadawcy";
$GLOBALS['TL_LANG']['tl_formdata']['mail_recipient']['0'] = "Odbiorca";
$GLOBALS['TL_LANG']['tl_formdata']['mail_recipient']['1'] = "Adres email odbiorcy";
$GLOBALS['TL_LANG']['tl_formdata']['mail_subject']['0'] = "Temat";
$GLOBALS['TL_LANG']['tl_formdata']['mail_subject']['1'] = "Temat maila potwierdzającego";
$GLOBALS['TL_LANG']['tl_formdata']['mail_body_plaintext']['0'] = "Wiadomość (czysty tekst)";
$GLOBALS['TL_LANG']['tl_formdata']['mail_body_plaintext']['1'] = "Tekst maila jako czysty tekst";
$GLOBALS['TL_LANG']['tl_formdata']['mail_body_html']['0'] = "Wiadomość (HTML)";
$GLOBALS['TL_LANG']['tl_formdata']['mail_body_html']['1'] = "Tekst maila jako HTML";
$GLOBALS['TL_LANG']['tl_formdata']['attachments'] = "Załączniki";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_details']['0'] = "Szczegóły";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_details']['1'] = "Pokaż szczegóły";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_edit']['0'] = "Edytuj";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_edit']['1'] = "Edytuj rekord";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_delete']['0'] = "Usuń";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_delete']['1'] = "Usuń rekord";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_export']['0'] = "Export CSV";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_export']['1'] = "Export rekordów jako plik CSV";
$GLOBALS['TL_LANG']['tl_formdata']['fe_deleteConfirm'] = "Czy naprawdę chcesz usunąć wpis?";
 
?>
