<?php
/**
 * TL_ROOT/system/modules/efg/languages/pl/tl_form_field.php 
 * 
 * TYPOlight extension: efg 1.10.4 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2008 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FFL']['efgLookupSelect']['0'] = "Rozwijana lista (DB)";
$GLOBALS['TL_LANG']['FFL']['efgLookupSelect']['1'] = "Rozwijana lista (DB) zawiera kilka pozycji, z których może być wybrana tylko jedna. Pozycje tego pola są pobierane ze zdefiniowanej tabeli bazy danych.";
$GLOBALS['TL_LANG']['FFL']['efgLookupCheckbox']['0'] = "Pola wielokrotnego wyboru (DB)";
$GLOBALS['TL_LANG']['FFL']['efgLookupCheckbox']['1'] = "Pola wielokrotnego wyboru (DB) zawiera jedną lub kilka pozycji, z których każde może być wybrane. Pozycje tego pola są pobierane ze zdefiniowanej tabeli bazy danych.";
$GLOBALS['TL_LANG']['FFL']['efgLookupRadio']['0'] = "Pola jednokrotnego wyboru (DB)";
$GLOBALS['TL_LANG']['FFL']['efgLookupRadio']['1'] = "Pola jednokrotnego wyboru (DB) zawiera kilka pozycji, z których może być wybrana tylko jedna. Pozycje tego pola są pobierane ze zdefiniowanej tabeli bazy danych.";
$GLOBALS['TL_LANG']['FFL']['efgImageSelect']['0'] = "Wybór obrazka";
$GLOBALS['TL_LANG']['FFL']['efgImageSelect']['1'] = "Wybór obrazka generuje galerię obrazków z polami jednokrotnego wyboru w formularzu.";
$GLOBALS['TL_LANG']['tl_form_field']['efgLookupOptions']['0'] = "Opcje bazy danych";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_field']['0'] = "Pole bazy danych (etykietka)";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_field']['1'] = "Wybierz pole z bazy danych, z którego powinny być pobierane dane (etykietki).";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_val_field']['0'] = "Pole bazy danych (wartość)";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_val_field']['1'] = "Wybierz pole z bazy danych, z którego powinny być pobierane dane (wartości).";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_where']['0'] = "Warunki";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_where']['1'] = "Jeśli chcesz wydobyć konkretne rekordy, możesz wprowadzić tutaj swoje warunki (e.g. <em>published='1'</em> or <em>type!='admin'</em>).";
$GLOBALS['TL_LANG']['tl_form_field']['efgMultiSRC']['0'] = "Pliki źródłowe";
$GLOBALS['TL_LANG']['tl_form_field']['efgMultiSRC']['1'] = "Zaznacz jeden lub więcej plików lub foldery (pliki z folderów będą dołączone automatycznie).";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSortBy']['0'] = "Sortuj";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSortBy']['1'] = "Wybierz porządek sortowania.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSize']['0'] = "Szerokość i wysokość obrazka";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSize']['1'] = "Wpisz szerokość albo wysokość obrazka lub oba te wymiary aby zeskalować obrazek. Jeśli pozostawisz te pola puste użyte zostaną oryginalne wymiary obrazka.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImagePerRow']['0'] = "Miniaturek w rzędzie";
$GLOBALS['TL_LANG']['tl_form_field']['efgImagePerRow']['1'] = "Wpisz ilość miniaturek w rzędzie.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageMargin']['0'] = "Margines obrazka";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageMargin']['1'] = "Wpisz margines górny, prawy, dolny i lewy oraz jednostki. Margines obrazka to przestrzeń pomiędzy obrazkiem a najbliższym mu elementem.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageFullsize']['0'] = "Widok w pełnych wymiarach";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageFullsize']['1'] = "Jeśli zaznaczysz tę opcję, obrazek, po kliknięciu, pokaże się w pełnych wymiarach.";
$GLOBALS['TL_LANG']['tl_form_field']['name_asc'] = "Nazwa pliku (rosnąco)";
$GLOBALS['TL_LANG']['tl_form_field']['name_desc'] = "Nazwa pliku (malejąco)";
$GLOBALS['TL_LANG']['tl_form_field']['date_asc'] = "Data (rosnąco)";
$GLOBALS['TL_LANG']['tl_form_field']['date_desc'] = "Data (malejąco)";
$GLOBALS['TL_LANG']['tl_form_field']['meta'] = "Plik meta (meta.txt)";
 
?>
