<?php
/**
 * TL_ROOT/system/modules/efg/languages/it/tl_efg_modules.php 
 * 
 * TYPOlight extension: efg 1.10.1 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2008 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Cristiano Gazzi (kroom), www.roomk.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['formdata'] = "Dati dei form";
$GLOBALS['TL_LANG']['MOD']['efg'] = "Dati dei form";
$GLOBALS['TL_LANG']['MOD']['feedback']['0'] = "Tutti i risultati";
$GLOBALS['TL_LANG']['MOD']['feedback']['1'] = "Dati memorizzati dai form.";
$GLOBALS['TL_LANG']['MOD']['formdata_from'] = "Dati memorizzati dal form";
$GLOBALS['TL_LANG']['MOD']['formdatalisting']['0'] = "Elenco dati del form";
$GLOBALS['TL_LANG']['MOD']['formdatalisting']['1'] = "Questo modulo ti permette di elencare nel frontend i record di una tabella di dati provenienti da un particolare form.";
$GLOBALS['TL_LANG']['FMD']['formdatalisting']['0'] = "Elenco dati del form";
$GLOBALS['TL_LANG']['FMD']['formdatalisting']['1'] = "Usa questo modulo per elencare nel frontend i record di una tabella di dati provenienti da un particolare form.";
$GLOBALS['TL_LANG']['tl_module']['list_formdata']['0'] = "Tabella dati del form";
$GLOBALS['TL_LANG']['tl_module']['list_formdata']['1'] = "Seleziona la tabella di dati di form che desideri elencare.";
$GLOBALS['TL_LANG']['tl_module']['efg_iconfolder']['0'] = "Cartella delle icone";
$GLOBALS['TL_LANG']['tl_module']['efg_iconfolder']['1'] = "Specifica la directory che contiene le tue icone. Se non compilato, saranno utilizzate le icone nella cartella \"system/modules/efg/html/\".";
$GLOBALS['TL_LANG']['tl_module']['efg_list_access']['0'] = "Restrizioni sulla visualizzazione";
$GLOBALS['TL_LANG']['tl_module']['efg_list_access']['1'] = "Scegli quali record devono essere visibili";
$GLOBALS['TL_LANG']['tl_module']['efg_DetailsKey']['0'] = "Identificatore di frammento URL per la pagina di dettaglio";
$GLOBALS['TL_LANG']['tl_module']['efg_DetailsKey']['1'] = "Invece che la chiave di default \"details\" puoi definire un'altra chiave usata per la URL della pagina di dettaglio.<br />In questo modo si può generare una URL come www.dominio.tld/pagina/<b>info<b>/alias.html, al posto della URL standard che sarebbe www.dominio.tld/pagina/<b>details<b>/alias.html";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_edit_access']['0'] = "Modifiche dal frontend";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_edit_access']['1'] = "Scegli l'opzione per abilitare la modifica dei record dal frontend";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_delete_access']['0'] = "Eliminazione dal frontend";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_delete_access']['1'] = "Scegli l'opzione per abilitare la cancellazione dei record dal frontend.";
$GLOBALS['TL_LANG']['efg_list_access']['public']['0'] = "Pubblico";
$GLOBALS['TL_LANG']['efg_list_access']['public']['1'] = "Qualsiasi visitatore è autorizzato a vedere tutti i record.";
$GLOBALS['TL_LANG']['efg_list_access']['member']['0'] = "Proprietario";
$GLOBALS['TL_LANG']['efg_list_access']['member']['1'] = "I membri sono autorizzati a vedere solo i record dei quali sono proprietari.";
$GLOBALS['TL_LANG']['efg_list_access']['groupmembers']['0'] = "Membri di gruppo";
$GLOBALS['TL_LANG']['efg_list_access']['groupmembers']['1'] = "I membri sono autorizzati a vedere solo i record dei quali sono proprietari, e i record dei membri del proprio gruppo.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['none']['0'] = "Niente modifiche dal frontend";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['none']['1'] = "I record non possono essere modificati dal frontend";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['public']['0'] = "Pubblico";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['public']['1'] = "Qualsiasi visitatore è autorizzato a modificare tutti i record.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['member']['0'] = "Proprietario";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['member']['1'] = "I membri sono autorizzati a modificare solo i record dei quali sono proprietari.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['groupmembers']['0'] = "Membri di gruppo";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['groupmembers']['1'] = "I membri sono autorizzati a modificare solo i record dei quali sono proprietari, e i record dei membri del proprio gruppo.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['none']['0'] = "Niente cancellazione dal frontend";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['none']['1'] = "I record non possono essere cancellatidal frontend.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['public']['0'] = "Pubblico";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['public']['1'] = "Qualsiasi visitatore è autorizzato a cancellare tutti i record.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['member']['0'] = "Proprietario";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['member']['1'] = "I membri sono autorizzati a cancellare solo i record dei quali sono proprietari.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['groupmembers']['0'] = "Membri di gruppo";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['groupmembers']['1'] = "I membri sono autorizzati a cancellare solo i record dei quali sono proprietari, e i record dei membri del proprio gruppo.";
 
?>
