<?php
/**
 * TL_ROOT/system/modules/efg/languages/it/tl_form.php 
 * 
 * TYPOlight extension: efg 1.10.1 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2008 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Cristiano Gazzi (kroom), www.roomk.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_form']['storeFormdata']['0'] = "Memorizza i dati nel modulo \"Dati dei form\"";
$GLOBALS['TL_LANG']['tl_form']['storeFormdata']['1'] = "Se scegli questa opzione, i dati saranno memorizzati nel database \"Dati dei moduli\".<br>Nota: Salvare questo form nuovamente dopo aver aggiunto o modificato campi del form";
$GLOBALS['TL_LANG']['tl_form']['useFormValues']['0'] = "Esporta valori dei campi";
$GLOBALS['TL_LANG']['tl_form']['useFormValues']['1'] = "Se scegli questa opzione, durante l'esportazione saranno esportati i valori dei campi invece che gli identificatori dei campi per i campi del modulo selezionato. Questo si applica ai tipi radio button, checkbox, e selezione.";
$GLOBALS['TL_LANG']['tl_form']['sendConfirmationMail']['0'] = "Invia conferma per e-mail";
$GLOBALS['TL_LANG']['tl_form']['sendConfirmationMail']['1'] = "Se scegli questa opzione, una conferma sarà inviata per e-mail al mittente del form.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailRecipientField']['0'] = "Campo del form contenente l'indirizzo e-mail del destinatario";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailRecipientField']['1'] = "Scegli il campo del form nel quale l'utente inserisce il suo indirizzo e-mail o un campo contenente l'indirizzo e-mail come valore.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailSender']['0'] = "Mittente";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailSender']['1'] = "Inserire l'indirizzo e-mail da usare come mittente.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailSubject']['0'] = "Oggetto";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailSubject']['1'] = "Inserire l'oggetto della mail di conferma. Se non inserisci un oggetto, aumenta la probabilità che la mail sia identificata come SPAM.";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailText']['0'] = "Testo della mail di conferma";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailText']['1'] = "Inserisci il testo della mail di conferma. Puoi usare gli insert tag standard o tag come .";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailTemplate']['0'] = "Template HTML per la mail di conferma";
$GLOBALS['TL_LANG']['tl_form']['confirmationMailTemplate']['1'] = "Se la mail di conferma va inviata come HTML, scegli il tuo template HTML dal file system.";
 
?>
