<?php
/**
 * TL_ROOT/system/modules/efg/languages/it/tl_formdata.php 
 * 
 * TYPOlight extension: efg 1.10.1 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2008 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Cristiano Gazzi (kroom), www.roomk.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_formdata']['form']['0'] = "Form";
$GLOBALS['TL_LANG']['tl_formdata']['form']['1'] = "Dati dal Form";
$GLOBALS['TL_LANG']['tl_formdata']['date']['0'] = "Data";
$GLOBALS['TL_LANG']['tl_formdata']['date']['1'] = "Data di inserimento";
$GLOBALS['TL_LANG']['tl_formdata']['ip']['0'] = "Indirizzo IP";
$GLOBALS['TL_LANG']['tl_formdata']['ip']['1'] = "Indirizzo IP del mittente";
$GLOBALS['TL_LANG']['tl_formdata']['be_notes']['0'] = "Note";
$GLOBALS['TL_LANG']['tl_formdata']['be_notes']['1'] = "Note, cose da fare, etc.";
$GLOBALS['TL_LANG']['tl_formdata']['published']['0'] = "Pubblicato";
$GLOBALS['TL_LANG']['tl_formdata']['published']['1'] = "Puoi usare questa opzione (published=1) come condizione di visualizzazione quando usi un modulo elenco.";
$GLOBALS['TL_LANG']['tl_formdata']['fd_member']['0'] = "Membro";
$GLOBALS['TL_LANG']['tl_formdata']['fd_member']['1'] = "Membro come proprietario di questo record";
$GLOBALS['TL_LANG']['tl_formdata']['fd_user']['0'] = "Utente";
$GLOBALS['TL_LANG']['tl_formdata']['fd_user']['1'] = "Utente come proprietario di questo record";
$GLOBALS['TL_LANG']['tl_formdata']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_formdata']['alias']['1'] = "Un alias è un riferimento unico al record che può essere richiamato invece dell'ID del record.";
$GLOBALS['TL_LANG']['tl_formdata']['new']['0'] = "Nuovo record";
$GLOBALS['TL_LANG']['tl_formdata']['new']['1'] = "Crea un nuovo record";
$GLOBALS['TL_LANG']['tl_formdata']['edit']['0'] = "Modifica record";
$GLOBALS['TL_LANG']['tl_formdata']['edit']['1'] = "Modifica il record ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['copy']['0'] = "Duplica record";
$GLOBALS['TL_LANG']['tl_formdata']['copy']['1'] = "Duplica il record ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['delete']['0'] = "Cancella record";
$GLOBALS['TL_LANG']['tl_formdata']['delete']['1'] = "Cancella record ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['show']['0'] = "Dettagli record";
$GLOBALS['TL_LANG']['tl_formdata']['show']['1'] = "Mostra dettagli record ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['mail']['0'] = "Invia mail di conferma";
$GLOBALS['TL_LANG']['tl_formdata']['mail']['1'] = "Invia mail di conferma per il record ID %s";
$GLOBALS['TL_LANG']['tl_formdata']['export']['0'] = "Esporta CSV";
$GLOBALS['TL_LANG']['tl_formdata']['export']['1'] = "Esporta i record in un file CSV";
$GLOBALS['TL_LANG']['tl_formdata']['exportxls']['0'] = "Esporta Excel";
$GLOBALS['TL_LANG']['tl_formdata']['exportxls']['1'] = "Esporta i record in un file MS Excel";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_details']['0'] = "Dettagli";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_details']['1'] = "Mostra dettagli";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_edit']['0'] = "Modifica";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_edit']['1'] = "Modifica record";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_delete']['0'] = "Cancella";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_delete']['1'] = "Cancella record";
$GLOBALS['TL_LANG']['tl_formdata']['fe_deleteConfirm'] = "Vuoi veramente cancellare la entry?";
 
?>
