<?php
/**
 * TL_ROOT/system/modules/efg/languages/de/tl_form_field.php
 *
 * TYPOlight extension: efg 1.10.3 stable
 * Deutsch translation file
 *
 * Copyright : (c) 2008 Thomas Kuhn
 * License   : GNU LGPL V3
 * Author    : Thomas Kuhn (tom)
 * Translator: Thomas Kuhn (tom)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['FFL']['efgLookupSelect']['0'] = "Select-Menü (DB)";
$GLOBALS['TL_LANG']['FFL']['efgLookupSelect']['1'] = "Ein Select-Menü (DB) ist ein \"Drop Down\" Menü mit mehreren Optionen von denen eine ausgewählt werden kann. Die Optionen werden aus einer definierbaren Datenbank-Tabelle gelesen.";
$GLOBALS['TL_LANG']['FFL']['efgLookupCheckbox']['0'] = "Checkbox-Menü (DB)";
$GLOBALS['TL_LANG']['FFL']['efgLookupCheckbox']['1'] = "Ein Checkbox-Menü (DB) ist ein mehrzeiliges Menü mit einer oder mehreren Optionen von denen beliebig viele ausgewählt werden können. Die Optionen werden aus einer definierbaren Datenbank-Tabelle gelesen.";
$GLOBALS['TL_LANG']['FFL']['efgLookupRadio']['0'] = "Radio-Button-Menü (DB)";
$GLOBALS['TL_LANG']['FFL']['efgLookupRadio']['1'] = "Ein Radio-Button-Menü (DB) ist ein mehrzeiliges Menü mit mehreren Optionen von denen eine ausgewählt werden kann. Die Optionen werden aus einer definierbaren Datenbank-Tabelle gelesen.";
$GLOBALS['TL_LANG']['FFL']['efgImageSelect']['0'] = "Bild-Auswahl-Menü";
$GLOBALS['TL_LANG']['FFL']['efgImageSelect']['1'] = "Ein Bild-Auswahl-Menü erzeugt im Formular eine Bilder-Galerie mit Radio-Buttons zur Auswahl eines Bildes.";
$GLOBALS['TL_LANG']['tl_form_field']['efgLookupOptions']['0'] = "Optionen aus Datenbank";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_field']['0'] = "Datenbank-Feld (label)";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_field']['1'] = "Wählen Sie, aus welchem Datenbank-Feld die auswählbaren Optionen (sichtbarer Text bzw. label) gelesen werden sollen.";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_val_field']['0'] = "Datenbank-Feld (value)";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_val_field']['1'] = "Wählen Sie, aus welchem Datenbank-Feld die auswählbaren Optionen (Absendewert bzw. value) gelesen werden sollen.";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_where']['0'] = "Bedingung";
$GLOBALS['TL_LANG']['tl_form_field']['lookup_where']['1'] = "Um bestimmte Datensätze auszuschließen, können Sie hier eine Bedingung eingeben (z.B. <em>published='1'</em> oder <em>type!='admin'</em>).";
$GLOBALS['TL_LANG']['tl_form_field']['efgMultiSRC']['0'] = "Quelldateien";
$GLOBALS['TL_LANG']['tl_form_field']['efgMultiSRC']['1'] = "Bitte wählen Sie alle Bilder und/oder Ordner, die in das Formularelement eingefügt werden sollen. Wenn Sie einen Ordner auswählen, werden alle darin enthaltenen Dateien automatisch eingefügt.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageUseHomeDir']['0'] = "Quelldateien aus Benutzerverzeichnis";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageUseHomeDir']['1'] = "Ist ein Benutzer angemeldet, werden anstelle der oben gewählten Quelldateien alle Bilder in seinem Benutzerverzeichnis in das Formularelement eingefügt.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSortBy']['0'] = "Sortieren nach";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSortBy']['1'] = "Bitte wählen Sie eine Sortierreihenfolge.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSize']['0'] = "Bildbreite und Bildhöhe";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageSize']['1'] = "Geben Sie entweder die Bildbreite, die Bildhöhe oder beide Werte ein, um die Bildgröße anzupassen. Wenn Sie keine Angaben machen, wird das Bild in seiner Originalgröße angezeigt.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImagePerRow']['0'] = "Vorschaubilder pro Reihe";
$GLOBALS['TL_LANG']['tl_form_field']['efgImagePerRow']['1'] = "Bitte legen Sie fest, wie viele Vorschaubilder pro Reihe angezeigt werden sollen.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageMargin']['0'] = "Bildabstand";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageMargin']['1'] = "Bitte geben Sie den oberen, rechten, unteren und linken Bildabstand sowie die Einheit ein. Der Bildabstand ist der Abstand zwischen einem Bild und seinen benachbarten Elementen.";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageFullsize']['0'] = "Großansicht";
$GLOBALS['TL_LANG']['tl_form_field']['efgImageFullsize']['1'] = "Wenn Sie diese Option wählen, öffnet sich bei Anklicken des Bildes dessen Großansicht.";
$GLOBALS['TL_LANG']['tl_form_field']['name_asc'] = "Dateiname (aufsteigend)";
$GLOBALS['TL_LANG']['tl_form_field']['name_desc'] = "Dateiname (absteigend)";
$GLOBALS['TL_LANG']['tl_form_field']['date_asc'] = "Datum (aufsteigend)";
$GLOBALS['TL_LANG']['tl_form_field']['date_desc'] = "Datum (absteigend)";
$GLOBALS['TL_LANG']['tl_form_field']['meta'] = "Meta Datei (meta.txt)";

?>
