<?php
/**
 * TL_ROOT/system/modules/efg/languages/de/tl_efg_modules.php
 *
 * TYPOlight extension: efg 1.10.4 stable
 * Deutsch translation file
 *
 * Copyright : (c) 2008 Thomas Kuhn
 * License   : GNU LGPL V3
 * Author    : Thomas Kuhn (tom)
 * Translator: Thomas Kuhn (tom)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Back end modules
 */
$GLOBALS['TL_LANG']['MOD']['formdata'] = "Formular-Daten";
$GLOBALS['TL_LANG']['MOD']['efg'] = "Formular-Daten";
$GLOBALS['TL_LANG']['MOD']['feedback'] = array("Feedback", "Gespeicherte Daten aus Formularen.");
$GLOBALS['TL_LANG']['MOD']['formdata_from'] = "Gespeicherte Daten aus Formular";
$GLOBALS['TL_LANG']['MOD']['formdatalisting'] = array("Auflistung Formular-Daten", "Mit diesem Modul können Sie eine beliebige Formular-Daten-Tabelle im Frontend auflisten.");

/**
 * Front end modules
 */
$GLOBALS['TL_LANG']['FMD']['formdatalisting'] = array("Auflistung Formular-Daten", "Verwenden Sie dieses Modul dazu, die Daten einer beliebigen Formular-Daten-Tabelle im Frontend aufzulisten.");

?>